### ISSUE TITLE
TRAFFIC MANAGER - wrong message when blocking an already blocked user

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#130]
If the user is already blocked and i try to block the user again it will show this message:
` Traffic Manager: The level of this user is already auto-blocked.`

**Comment by pulsar-de** [comment]
What's wrong with it?
If a user was manually blocked and you try to block him again the msg is:
`Traffic Manager: User  <NICK>  is already blocked by:  <NICK>  |  Reason: <REASON>`
And if a user was auto blocked (because of sharelimit) and you try to block him again the msg is:
`Traffic Manager: The level of this user is already auto-blocked.`

That's exactly what i expect.

**Comment by Sopor** [comment]
Aleady fixed in #37
