### ISSUE TITLE
force keyprint connections

### ISSUE THREAD

**Issue by vildsvin666** [luadch/luadch#135]
Hello!
How can I force only connections with keyprint and deny all other connections? :)

**Comment by pulsar-de** [comment]
Thats not possible, because there is no way to determine whether the client is using the keyprint in the address field.

The keyprint is the checksum of the hub certificate. If a client uses this keyprint in the address field, he can compare whether this checksum matches the hub certificate. There are clients e.g. [AirDC](https://www.airdcpp.net/) that offer the option of refusing the connection in their security settings if they do not match the hubcert.

**Comment by pulsar-de** [comment]
After a conversation in the dc, here is an addendum to clear up any misunderstandings:

The ADC protocol specs do not require the client to send this type of information to the hub. However, if the client does not send any information about whether the client is using a keyprint in the address field, the hub software cannot evaluate this either. If the hub does not know anything about it, it cannot take any precautionary measures.
