### ISSUE TITLE
cmd_accinfo.lua - bad argument #1 to 'find' (string expected, got nil)

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#141]
When running +accinfo i get this error message:
```
scripts.lua: script error: ././scripts/cmd_accinfo.lua:306: bad argument #1 to 'find' (string expected, got nil) (listener: onBroadcast; script: 'cmd_accinfo.lua')
```

Luadch 2.23 RC7

**Comment by corruptview** [comment]
> When running +accinfo i get this error message:
> 
> ```
> scripts.lua: script error: ././scripts/cmd_accinfo.lua:306: bad argument #1 to 'find' (string expected, got nil) (listener: onBroadcast; script: 'cmd_accinfo.lua')
> ```
> 
> Luadch 2.23 RC7

Same for me

**Comment by pulsar-de** [comment]
The problem is the "search_flag_blocked".
the "cmd_accinfo.lua" script searches the descriptions of the users and checks whether someone has this "search_flag_blocked".
if you change the "flag_blocked" in the "etc_trafficmanager.lua" script, which you shouldn't do because it is not in the settings area but in the code area, then it no longer matches the search string of the "cmd_accinfo.lua" script.

I will move this "flag_blocked" to the "cmd_trafficmanager.lua" settings in "cfg/cfg.tbl", that should avoid this issue.

**Comment by Sopor** [comment]
@pulsar-de 
It seems that this isn't fixed. I still get:
```
script error: ././scripts/cmd_accinfo.lua:348: bad argument #1 to 'find' (string expected, got nil) (listener: onBroadcast; script: 'cmd_accinfo.lua')
```
when running Accinfo by right clicking on a user and select Show / Accinfo.

In main i also get this message: `Unknown command. Check leading spaces and syntax.`

If i run `+accinfo nick <nick>` in main it works. Same if i run `+accinfo sid <sid>`

Tested in Luadch 2.23 RC9, 2.23, 2.24 RC1 with the same result.
