### ISSUE TITLE
SID/CID

### ISSUE THREAD

**Issue by Ninja-FSE** [luadch/luadch#152]
What does this means and how does it works?

got an [FAILED AUTHENTICATION] Reason: Your CID is taken.

**Comment by Sopor** [comment]
It happens when the user disconnects without the hub knows it. It is quite annoying and you can disable it by comment it out:

open core/hub.lua and add `--` in front of the row (in my case row 1776):
```
--scripts_firelistener( "onFailedAuth", nick, userip, cid, _i18n_cid_taken )
```

`+reload` doesn't work when you make changes in core, so you need to restart Luadch.

I hope there will be a real fix for it soon.

**Comment by Ninja-FSE** [comment]
Okey cool thanks for the info! Merry Christmas!

**Comment by blasti** [comment]
Listener "onFailedAuth" was introduced in 384c17c174280d925ca5d14cfce0211612d20d20.
Not sure why, probably to inform OPs. Need to study the code.
