### ISSUE TITLE
Can't set minshare without redirect

### ISSUE THREAD

**Issue by Tantrix** [luadch/luadch#165]
>     usr_share_redirect = false,  -- use redirect instead of disconnect? (boolean)

>     min_share = {  -- min share in giga byte (array of integer)
> 
>         [ 0 ] = 1,  -- unreg (default = 0 giga byte)

Still, 0 bytes shared users allowed.

>     usr_share_redirect = true,  -- use redirect instead of disconnect? (boolean)

Prevents those users from connecting.

**Comment by pulsar-de** [comment]
Just trying to reproduce:

Without redirect:
`[19:11:02] <Luadch Hub> [ USER SHARE ]--> Hub min share:  1.00 GB  |  Hub max share:  200.00 TB  |  Your share:  0 B`

With redirect:
`[19:16:43] *** [ USER SHARE ]--> You got redirected because:  [ USER SHARE ]--> Hub min share:  1.00 GB  |  Hub max share:  200.00 TB  |  Your share:  0 B`

Worked as it should.

**Comment by Tantrix** [comment]
What settings should I check additionally?

**Comment by pulsar-de** [comment]
I can only think of the trafficblocker. Instead of a disconnet, he can use the blocker if the user has not enough share.

If:
`etc_trafficmanager_activate = true, -- activate this script? (boolean)`
And:
`etc_trafficmanager_check_minshare = true,  -- block user instead of disconnect if usershare < minshare? This feature checks all users < oplevel (boolean)`

**Comment by Tantrix** [comment]
Yepp, it worked.

I should note `etc_trafficmanager.lua` was disabled via scripts array previously.

Is it not the same as `activate = false` setting?

**Comment by pulsar-de** [comment]
No, it's not the same, there are dependencies in other scripts.
Issue solved?
