### ISSUE TITLE
2.23 x86

### ISSUE THREAD

**Issue by Tantrix** [luadch/luadch#175]
Is there x86 Windows version? My netbook can't run x64 apps.

**Comment by blasti** [comment]
No. I would need to setup a virtual machine with Win32 and a 32-bit compiler toolchain. Maybe you should try it:

0) Checkout latest luadch source via git.
1) Follow the instructions to install the necessary toolchain on your netbook (use x86 versions instead of x64): https://github.com/luadch/luadch/blob/09b4728a49263a4dc1d5cf40bbaa913bbbd705ec/compile_with_mingw.bat#L3
2) Adjust the path settings and use compile_with_mingw.bat to compile the hub.

Good luck!

**Comment by Sopor** [comment]
@Tantrix It isn't that easy as follow those instructions. You will have to struggle with a few issues on the way.

I have compiled a version for you. See if you get it to run before you go live with it.

[Luadch-2.24-RC1-2022-04-14-Win-x86_32.zip](https://github.com/luadch/luadch/files/8492581/Luadch-2.24-RC1-2022-04-14-Win-x86_32.zip)

**Comment by Sopor** [comment]
It seems that you can use Windows x64 if you install and use the 32-bits MinGW and OpenSSL.

You can set the path in the bat file very easy, but don't forget to include Windows and System32 :)
```
set path=C:\Windows\System32;C:\Windows;C:\MinGW-32\bin;C:\OpenSSL-Win32\bin

set openssl_headers=C:\openssl-3.0.2-win32-mingw\include
set openssl_libs=C:\openssl-3.0.2-win32-mingw\lib
set openssl_bin=C:\openssl-3.0.2-win32-mingw\bin
```

**Comment by Tantrix** [comment]
@Sopor Yes, it works, thx.

Not sure however if I gonna try compiling luadch by myself soon (:

**Comment by pulsar-de** [comment]
OK, i think then we can put the lid on the top here ;)
