### ISSUE TITLE
New created accounts need to be logged in or else they will be deleted...

### ISSUE THREAD

**Issue by Sopor** [luadch/luadch#49]
When you create an account there should be a time limit and if the user never login before X days the account will be deleted and reported to OP_Chat that this account that was created by is now deleted.

**Comment by pulsar-de** [comment]
This is not exactly what was meant by the wish, but I think with this script the wish will still be fulfilled: [cmd_usercleaner.lua](https://github.com/luadch/luadch/blob/master/scripts/cmd_usercleaner.lua)

Among other things, this script offers the possibility to find and delete "registered but unused user accounts". An expiration date can also be set. This script is a part of Luadch since v2.23 RC2
