### ISSUE TITLE
User disconnect before getting reg info PM

### ISSUE THREAD

**Issue by HadesDCH** [luadch/luadch#83]
While registering a user - person that registers gets pm with login info ok however  user thats being registered gets disconnect before that PM. Thus never gets reg info.

**Comment by luadchuser** [comment]
Yes, this is a pretty irritating bug.
As soon as you reg someone, they disconnect, without any way of knowing their password.
I'll run through the code and see if I can find a fix, because otherwise, right now, you need to give a password in advance, then reg, then change the password to match the one you gave. That's not exactly slick. You also then need to mess with the "badpassword" values to make sure they don't get locked out.

**Comment by HadesDCH** [comment]
Looks like this bug wasn't fixed yet with new 2.21 release.

**Comment by pulsar-de** [comment]
This fixed  [cmd_reg.lua](https://github.com/luadch/luadch/blob/master/scripts/cmd_reg.lua)  should solve the problem.
