### ISSUE TITLE
v2.20 for linux-x64 or x86

### ISSUE THREAD

**Issue by cnadolny2s** [luadch/luadch#88]
When will you release these assets?

**Comment by blasti** [comment]
Try this:

[https://github.com/luadch/luadch/releases/download/v2.20/luadch-2.20-linux-x64.tar.gz](https://github.com/luadch/luadch/releases/download/v2.20/luadch-2.20-linux-x64.tar.gz)

Otherwise, to compile yourself, do the following in your shell:

```
git clone https://github.com/luadch/luadch.git
cd luadch
./compile
```
If everything went fine, the hub can be found in the `build_gcc` directory.

**Comment by cnadolny2s** [comment]
Cool, thanks for the instruction and adding it to the asset list! Love your project.
