### ISSUE TITLE
New v. 2.21 wont serve on TLS port when certs genned via LUACERT MANAGER.

### ISSUE THREAD

**Issue by HadesDCH** [luadch/luadch#89]
Not sure if this is certs manager issue or maybe openssl version i have installed on my windows pc.
After generating certs using luacert manager  hub serves on adc port fine  but im unable to connect on adcs address (timed out).
I checked firewall port is open, LUADCHUB is added as allowed firewall app, not sure if this is a bug or my missconfig / setup issue. I see no errors enywhere.

**Comment by blasti** [comment]
I've updated the package and included OpenSSL 1.1.1f DLLs into it.

1. Download and unpack the updated package [https://github.com/luadch/luadch/releases/download/v2.21/Luadch-2.21-Win-x86_64.zip](https://github.com/luadch/luadch/releases/download/v2.21/Luadch-2.21-Win-x86_64.zip)

2. Use `make_cert.bat` in `certs` folder to create a new cert

3. Start hub, try to login.

If everything went fine, the error was caused by the missing DLLs. You can then try to copy them into your current luadch installation. Or use above package for a new installation.

**Comment by pulsar-de** [comment]
> Not sure if this is certs manager issue or maybe openssl version i have installed on my windows pc

It's your OpenSSL version. certs created with Luadch [Certmanager](https://github.com/luadch/certmanager) for TLSv1.2 are still compatible with TLSv1.3.
