### ISSUE TITLE
Make it possible to bind to specific ip-address(es), not just 0.0.0.0/::

### ISSUE THREAD

**Issue by seabert** [luadch/luadch#9]
It would be nice if it would be possible to let luadch bind to specific ip-address(es). I have multiple ip-addresses at my VPS and I don't want luadch to listen on all of them. I've seen in `server.lua` that the code is ready for this, so a simple change should suffice.

**Comment by blasti** [comment]
I merged tarulas fix,
now you can add a new option like this to the cfg.tbl:

hub_listen = { "x.x.x.x", "y.y.y.y", "z.z.z.z" },

Hope that helps.

**Comment by Sopor** [comment]
It would be much better if i could use my network interface name. If you bind it to a public IP address and you get a new IP address (DHCP) you will need to change it in Luadch too. Instead it should be possible to use eth0 or in Windows you get as default "Local area network" but it is possible to change it to whatever you want. This is what Luadch should use instead of binding to an IP address.
I have two networks card in my computer, one have a public IP address and the other is my LAN. I have binded all my programs to use my public IP address and only one program use my network name. All the other programs will complain that it can't find the IP address anymore when i get a new one. It will not happen so often but it is still annoying when it happens. If you have an ISP that give you a new IP address every 24 hours it is not fun to shutdown Luadch every 24 hours to change IP address.

**Comment by blasti** [comment]
you can also use  hostnames, e. g.

hub_listen = { "localhost", "192.168.2.1", "blabla.no-ip.org"},

**Comment by seabert** [comment]
Or just leave it empty to bind to all interface (i.e. behave as before), I presume?

**Comment by Sopor** [comment]
@seabert the problem was that i don't want it to connect from LAN so i bind it to my public IP address but if it works like @blasti says that i can even add a ddns, then it should be enough (i think). I have never seen this before though, so is this really to "bind" an IP address?

**Comment by blasti** [comment]
from the luasocket manual:

>  master:bind(address, port)
> Binds a master object to address and port on the local host.
> Address can be an IP address or a host name.
